/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Bootstrap */
        get: operations["runtime_bootstrap_api_v1_runtime_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Settings */
        get: operations["runtime_settings_api_v1_runtime_settings_get"];
        /** Update Runtime Settings */
        put: operations["update_runtime_settings_api_v1_runtime_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canon/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Canon */
        get: operations["current_canon_api_v1_canon_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Project */
        patch: operations["patch_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace */
        get: operations["workspace_api_v1_projects__project_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/planner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Planner */
        get: operations["planner_api_v1_projects__project_id__planner_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/planner/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Planner Message */
        post: operations["planner_message_api_v1_projects__project_id__planner_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/planner/proposals/{proposal_id}/adopt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adopt Proposal */
        post: operations["adopt_proposal_api_v1_projects__project_id__planner_proposals__proposal_id__adopt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stories */
        get: operations["stories_api_v1_projects__project_id__stories_get"];
        put?: never;
        /** Create Story */
        post: operations["create_story_api_v1_projects__project_id__stories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/stories/{story_version_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Story */
        post: operations["activate_story_api_v1_projects__project_id__stories__story_version_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/shot-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shot Plans */
        get: operations["shot_plans_api_v1_projects__project_id__shot_plans_get"];
        put?: never;
        /** Create Shot Plan */
        post: operations["create_shot_plan_api_v1_projects__project_id__shot_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/shot-plans/{shot_plan_version_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Shot Plan */
        post: operations["activate_shot_plan_api_v1_projects__project_id__shot_plans__shot_plan_version_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assets */
        get: operations["assets_api_v1_projects__project_id__assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset */
        get: operations["asset_api_v1_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/assets/{asset_id}/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Diagnose Asset */
        post: operations["diagnose_asset_api_v1_projects__project_id__assets__asset_id__diagnose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/assets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Asset */
        post: operations["upload_asset_api_v1_projects__project_id__assets_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/selections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Asset */
        post: operations["select_asset_api_v1_projects__project_id__selections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/asset-generations/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Asset Generation */
        post: operations["preview_asset_generation_api_v1_projects__project_id__asset_generations_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/asset-generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Asset Generation */
        post: operations["create_asset_generation_api_v1_projects__project_id__asset_generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/video-generations/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Video */
        post: operations["preview_video_api_v1_projects__project_id__video_generations_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/video-generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Video Job */
        post: operations["create_video_job_api_v1_projects__project_id__video_generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/edits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Edits */
        get: operations["edits_api_v1_projects__project_id__edits_get"];
        put?: never;
        /** Create Edit */
        post: operations["create_edit_api_v1_projects__project_id__edits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Export */
        post: operations["create_export_api_v1_projects__project_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/final-selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Final Selection */
        post: operations["final_selection_api_v1_projects__project_id__final_selection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset Content */
        get: operations["asset_content_api_v1_assets__asset_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetDto */
        AssetDto: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Projectid */
            projectId?: string | null;
            /** Producingjobid */
            producingJobId?: string | null;
            /** Candidateindex */
            candidateIndex?: number | null;
            /** Role */
            role: string;
            /**
             * Mediatype
             * @enum {string}
             */
            mediaType: "image" | "video" | "audio";
            /** Storagekey */
            storageKey: string;
            /** Sha256 */
            sha256: string;
            /** Bytesize */
            byteSize: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** AssetGenerationCommand */
        AssetGenerationCommand: {
            /** Expectedinputhash */
            expectedInputHash: string;
            /** Expectedcostmicros */
            expectedCostMicros: number;
            /** Idempotencykey */
            idempotencyKey: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "episode_child" | "episode_cat" | "pair_scale" | "environment" | "style_board";
        };
        /** AssetGenerationPreviewCommand */
        AssetGenerationPreviewCommand: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "episode_child" | "episode_cat" | "pair_scale" | "environment" | "style_board";
        };
        /** AssetGenerationPreviewDto */
        AssetGenerationPreviewDto: {
            /** Inputhash */
            inputHash: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "episode_child" | "episode_cat" | "pair_scale" | "environment" | "style_board";
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Capabilityrevision */
            capabilityRevision: string;
            /** Prompt */
            prompt: string;
            /** Negativeprompt */
            negativePrompt: string;
            /** References */
            references: components["schemas"]["CompiledReference"][];
            /** Expectedcostmicros */
            expectedCostMicros: number;
            /** Warnings */
            warnings?: {
                [key: string]: string;
            }[];
        };
        /** Body_upload_asset_api_v1_projects__project_id__assets_upload_post */
        Body_upload_asset_api_v1_projects__project_id__assets_upload_post: {
            /** File */
            file: string;
        };
        /** CompiledReference */
        CompiledReference: {
            /**
             * Assetid
             * Format: uuid
             */
            assetId: string;
            /**
             * Role
             * @enum {string}
             */
            role: "episode_child" | "episode_cat" | "pair_scale" | "environment" | "style_board" | "style_source";
            /** Sha256 */
            sha256: string;
            /** Priority */
            priority: number;
            /** Included */
            included: boolean;
            /** Omittedreason */
            omittedReason?: string | null;
        };
        /** EditCreateCommand */
        EditCreateCommand: {
            edl: components["schemas"]["EditDecisionListDto"];
        };
        /** EditDecisionListDto */
        EditDecisionListDto: {
            /** Sourcevideoselections */
            sourceVideoSelections: components["schemas"]["EditSourceDto"][];
            /** Transitions */
            transitions?: components["schemas"]["EditTransitionDto"][];
            /**
             * Audiopolicy
             * @enum {string}
             */
            audioPolicy: "native" | "mute" | "native_fades";
            output: components["schemas"]["EditOutputDto"];
        };
        /** EditOutputDto */
        EditOutputDto: {
            /**
             * Aspectratio
             * @constant
             */
            aspectRatio: "9:16";
            /**
             * Width
             * @constant
             */
            width: 720;
            /**
             * Height
             * @constant
             */
            height: 1280;
            /**
             * Format
             * @constant
             */
            format: "mp4";
        };
        /** EditSourceDto */
        EditSourceDto: {
            /**
             * Assetid
             * Format: uuid
             */
            assetId: string;
            /** Sha256 */
            sha256: string;
            /** Startms */
            startMs: number;
            /** Endms */
            endMs: number;
        };
        /** EditTransitionDto */
        EditTransitionDto: {
            /** Afterclipindex */
            afterClipIndex: number;
            /**
             * Type
             * @enum {string}
             */
            type: "none" | "fade" | "crossfade";
            /** Durationms */
            durationMs: number;
        };
        /** EditVersionDto */
        EditVersionDto: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /** Revision */
            revision: number;
            /** Sourceselectionhash */
            sourceSelectionHash: string;
            edl: components["schemas"]["EditDecisionListDto"];
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "rendered" | "approved";
            /** Renderedassetid */
            renderedAssetId?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ExportCommand */
        ExportCommand: {
            /**
             * Editversionid
             * Format: uuid
             */
            editVersionId: string;
            /** Idempotencykey */
            idempotencyKey: string;
        };
        /** FinalSelectionCommand */
        FinalSelectionCommand: {
            /**
             * Assetid
             * Format: uuid
             */
            assetId: string;
        };
        /** GenerationCommand */
        GenerationCommand: {
            /** Expectedinputhash */
            expectedInputHash: string;
            /** Expectedcostmicros */
            expectedCostMicros: number;
            /** Idempotencykey */
            idempotencyKey: string;
        };
        /** GenerationPreviewDto */
        GenerationPreviewDto: {
            /** Inputhash */
            inputHash: string;
            /**
             * Kind
             * @default video
             * @constant
             */
            kind: "video";
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Capabilityrevision */
            capabilityRevision: string;
            /** Prompt */
            prompt: string;
            /** Negativeprompt */
            negativePrompt: string;
            /** References */
            references: components["schemas"]["CompiledReference"][];
            /** Expectedcostmicros */
            expectedCostMicros: number;
            /**
             * Storyversionid
             * Format: uuid
             */
            storyVersionId: string;
            /**
             * Shotplanversionid
             * Format: uuid
             */
            shotPlanVersionId: string;
            /** Selectionhash */
            selectionHash: string;
            /** Warnings */
            warnings?: {
                [key: string]: string;
            }[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageDiagnosisCommand */
        ImageDiagnosisCommand: {
            /**
             * Assetid
             * Format: uuid
             */
            assetId: string;
            /** Idempotencykey */
            idempotencyKey: string;
            /**
             * Expectedcostmicros
             * @default 0
             * @constant
             */
            expectedCostMicros: 0;
        };
        /** JobDto */
        JobDto: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "plan_story" | "generate_image" | "diagnose_image" | "generate_video" | "render_export";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "submitting" | "submitted" | "polling" | "storing" | "succeeded" | "failed" | "cancel_requested" | "cancelled";
            /** Inputhash */
            inputHash: string;
            /** Idempotencykey */
            idempotencyKey: string;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Providertaskid */
            providerTaskId?: string | null;
            /** Expectedcostmicros */
            expectedCostMicros?: number | null;
            /** Frozeninput */
            frozenInput: {
                [key: string]: unknown;
            };
            /** Resultassetids */
            resultAssetIds?: string[];
            /** Supersedesjobid */
            supersedesJobId?: string | null;
            /** Error */
            error?: {
                [key: string]: unknown;
            } | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** LifeClipSpec */
        LifeClipSpec: {
            /** Durationseconds */
            durationSeconds: number;
            /**
             * Aspectratio
             * @constant
             */
            aspectRatio: "9:16";
            /** Microevent */
            microEvent: string;
            /** Childaction */
            childAction: string;
            /** Catactionorobservation */
            catActionOrObservation: string;
            /** Visiblecauseandeffect */
            visibleCauseAndEffect: string;
            /** Warmending */
            warmEnding: string;
            /**
             * Dialoguepolicy
             * @enum {string}
             */
            dialoguePolicy: "none" | "minimal";
            /** Environmentintent */
            environmentIntent: string;
            /** Propintent */
            propIntent?: string | null;
        };
        /** LifeStoryProposalDto */
        LifeStoryProposalDto: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "adopted" | "outdated";
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Body */
            body: string;
            microEvent: components["schemas"]["MicroEvent"];
            /** Targetdurationseconds */
            targetDurationSeconds: number;
            /**
             * Dialoguepolicy
             * @enum {string}
             */
            dialoguePolicy: "none" | "minimal";
            /** Environmentintent */
            environmentIntent: string;
            /** Propintent */
            propIntent?: string | null;
            /** Contexthash */
            contextHash: string;
            /** Warnings */
            warnings?: {
                [key: string]: string;
            }[];
        };
        /** MicroEvent */
        MicroEvent: {
            /** Trigger */
            trigger: string;
            /** Childaction */
            childAction: string;
            /** Catresponse */
            catResponse: string;
            /** Visiblechange */
            visibleChange: string;
            /** Warmending */
            warmEnding: string;
        };
        /** PlannerMessageCommand */
        PlannerMessageCommand: {
            /** Text */
            text: string;
            /** Expectedcontextrevision */
            expectedContextRevision: number;
            /** Idempotencykey */
            idempotencyKey: string;
        };
        /** PlannerMessageDto */
        PlannerMessageDto: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /** Ordinal */
            ordinal: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** PlannerSnapshotDto */
        PlannerSnapshotDto: {
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /** Contextrevision */
            contextRevision: number;
            /** Messages */
            messages: components["schemas"]["PlannerMessageDto"][];
            /** Proposals */
            proposals: components["schemas"]["LifeStoryProposalDto"][];
        };
        /** PreviewCommand */
        PreviewCommand: {
            /**
             * Maximumreferences
             * @default 4
             */
            maximumReferences: number;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Title */
            title: string;
            /** Theme */
            theme: string;
            /** Targetdurationseconds */
            targetDurationSeconds: number;
        };
        /** ProjectDto */
        ProjectDto: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Theme */
            theme: string;
            /** Targetdurationseconds */
            targetDurationSeconds: number;
            /** Aspectratio */
            aspectRatio: string;
            /**
             * Canonprofileid
             * Format: uuid
             */
            canonProfileId: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ProjectPatch */
        ProjectPatch: {
            /** Title */
            title?: string | null;
            /** Theme */
            theme?: string | null;
            /** Targetdurationseconds */
            targetDurationSeconds?: number | null;
        };
        /** ProjectSelectionDto */
        ProjectSelectionDto: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /**
             * Assetid
             * Format: uuid
             */
            assetId: string;
            /** Slot */
            slot: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "selected" | "rejected" | "approved";
            /** Sourcehash */
            sourceHash: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** SelectionCommand */
        SelectionCommand: {
            /** Slot */
            slot: string;
            /**
             * Assetid
             * Format: uuid
             */
            assetId: string;
        };
        /** ShotPlanDraft */
        ShotPlanDraft: {
            /**
             * Sourcestoryversionid
             * Format: uuid
             */
            sourceStoryVersionId: string;
            /** Sourceselectionhash */
            sourceSelectionHash: string;
            clip: components["schemas"]["LifeClipSpec"];
            /** Shots */
            shots: components["schemas"]["ShotSpec"][];
        };
        /** ShotPlanVersionDto */
        ShotPlanVersionDto: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /** Revision */
            revision: number;
            /**
             * Sourcestoryversionid
             * Format: uuid
             */
            sourceStoryVersionId: string;
            /** Sourceselectionhash */
            sourceSelectionHash: string;
            /** Clip */
            clip: {
                [key: string]: unknown;
            };
            /** Shots */
            shots: components["schemas"]["ShotSpec"][];
            /** Totaldurationseconds */
            totalDurationSeconds: number;
            /** Active */
            active: boolean;
            /**
             * Outdated
             * @default false
             */
            outdated: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ShotSpec */
        ShotSpec: {
            /** Id */
            id: string;
            /** Order */
            order: number;
            /** Durationseconds */
            durationSeconds: number;
            /** Framing */
            framing: string;
            /** Cameramovement */
            cameraMovement: string;
            /** Childaction */
            childAction: string;
            /** Cataction */
            catAction: string;
            /** Environmentchange */
            environmentChange: string;
            /**
             * Transition
             * @enum {string}
             */
            transition: "continuous" | "soft_cut" | "hard_cut";
        };
        /** StoryCreateCommand */
        StoryCreateCommand: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            microEvent: components["schemas"]["MicroEvent"];
            /** Targetdurationseconds */
            targetDurationSeconds: number;
            /**
             * Dialoguepolicy
             * @enum {string}
             */
            dialoguePolicy: "none" | "minimal";
            /** Environmentintent */
            environmentIntent: string;
        };
        /** StoryVersionDto */
        StoryVersionDto: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /** Revision */
            revision: number;
            /** Sourceproposalid */
            sourceProposalId?: string | null;
            /** Title */
            title: string;
            /** Body */
            body: string;
            microEvent: components["schemas"]["MicroEvent"];
            /** Targetdurationseconds */
            targetDurationSeconds: number;
            /**
             * Dialoguepolicy
             * @enum {string}
             */
            dialoguePolicy: "none" | "minimal";
            /** Environmentintent */
            environmentIntent: string;
            /** Active */
            active: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    runtime_bootstrap_api_v1_runtime_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    runtime_settings_api_v1_runtime_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    update_runtime_settings_api_v1_runtime_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_canon_api_v1_canon_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDto"][];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_api_v1_projects__project_id__workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    planner_api_v1_projects__project_id__planner_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannerSnapshotDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    planner_message_api_v1_projects__project_id__planner_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannerMessageCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adopt_proposal_api_v1_projects__project_id__planner_proposals__proposal_id__adopt_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryVersionDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stories_api_v1_projects__project_id__stories_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryVersionDto"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_story_api_v1_projects__project_id__stories_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryCreateCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryVersionDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_story_api_v1_projects__project_id__stories__story_version_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                story_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryVersionDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shot_plans_api_v1_projects__project_id__shot_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotPlanVersionDto"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_shot_plan_api_v1_projects__project_id__shot_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShotPlanDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotPlanVersionDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_shot_plan_api_v1_projects__project_id__shot_plans__shot_plan_version_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                shot_plan_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotPlanVersionDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assets_api_v1_projects__project_id__assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDto"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_api_v1_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnose_asset_api_v1_projects__project_id__assets__asset_id__diagnose_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageDiagnosisCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_asset_api_v1_projects__project_id__assets_upload_post: {
        parameters: {
            query: {
                role: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_asset_api_v1_projects__project_id__assets_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_asset_api_v1_projects__project_id__selections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSelectionDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_asset_generation_api_v1_projects__project_id__asset_generations_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetGenerationPreviewCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetGenerationPreviewDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_asset_generation_api_v1_projects__project_id__asset_generations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetGenerationCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_video_api_v1_projects__project_id__video_generations_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationPreviewDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_video_job_api_v1_projects__project_id__video_generations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_events_get: {
        parameters: {
            query?: {
                afterEventId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edits_api_v1_projects__project_id__edits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditVersionDto"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_edit_api_v1_projects__project_id__edits_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditCreateCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditVersionDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_api_v1_projects__project_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    final_selection_api_v1_projects__project_id__final_selection_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalSelectionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSelectionDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_content_api_v1_assets__asset_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
